### ISSUE TITLE
Undefined behavior in Json5ReadArchive

### ISSUE THREAD

**Issue by bmartin427** [mjbots/mjlib#1]
On https://github.com/mjbots/mjlib/blob/master/mjlib/base/json5_read_archive.h#L520 , two function calls that both read from the stream appear in the same line.  The order these function calls gets made is undefined, but one of the two possible orderings by the compiler will result in the exponent string being dropped.

A similar problem appears at https://github.com/mjbots/mjlib/blob/master/mjlib/base/json5_read_archive.h#L526

**Comment by jpieper** [comment]
Thanks Brad!

**Comment by bmartin427** [comment]
Thank you! :smile:
